[package]
name = "thumbor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
axum = "0.7.5"
base64 = "0.22.1"
bytes = "1.7.2"
prost = "0.13.2"

[build-dependencies]
prost-build = "0.13.2"
